package com.sanly.notifications.entity;

public enum EventType {
    // Data access events
    DATA_ACCESSED_BY_POLICE,
    DATA_ACCESSED_BY_TAX,
    DATA_ACCESSED_BY_DMV,
    DATA_ACCESSED_BY_MEDICAL,
    DATA_ACCESSED_BY_BUSINESS,
    DATA_ACCESSED_UNKNOWN_INSTITUTION,

    // Record changes
    DRIVING_LICENSE_ISSUED,
    DRIVING_LICENSE_SUSPENDED,
    MEDICAL_RECORD_ADDED,
    VISION_TEST_EXPIRING_SOON,
    TAX_STATUS_CHANGED,
    BUSINESS_REGISTRATION_APPROVED,
    BUSINESS_REGISTRATION_REJECTED,
    CRIMINAL_RECORD_ADDED,
    CIVIL_BIRTH_REGISTERED,
    CIVIL_MARRIAGE_REGISTERED,
    CIVIL_DEATH_REGISTERED,

    // Security events
    ANOMALY_DETECTED_ON_YOUR_DATA,
    SUSPICIOUS_ACCESS_DETECTED,

    // Account events
    CITIZEN_STATUS_CHANGED,
    PASSWORD_CHANGED,

    // Prescription events
    PRESCRIPTION_ISSUED,
    PRESCRIPTION_DISPENSED,

    // Life event automation
    CHILD_BENEFIT_TRIGGERED,
    SCHOOL_ENROLLMENT_REMINDER,
    VACCINATION_DUE_SOON,
    BENEFITS_CANCELLED_DECEASED,
    BUSINESS_OWNER_DECEASED,
    MARRIAGE_TAX_INFO,
    DIVORCE_TAX_INFO,

    // Education events
    DIPLOMA_ISSUED,
    DIPLOMA_REVOKED,
    ENROLLMENT_CONFIRMED,
    SCHOOL_ENROLLMENT_QUEUED,

    // Land registry events
    PROPERTY_TRANSFER_INITIATED,
    PROPERTY_TRANSFER_APPROVED,
    PROPERTY_TRANSFER_REJECTED,
    PROPERTY_INHERITANCE_PENDING,

    // Social benefits events
    BENEFIT_CLAIM_APPROVED,
    BENEFIT_CLAIM_REJECTED,
    BENEFIT_AUTO_TRIGGERED,
    BENEFIT_PAYMENT_SCHEDULED,
    PENSION_ELIGIBLE,
    UNEMPLOYMENT_BENEFIT_EXPIRED,
    MARRIAGE_BENEFIT_INFO,

    // Customs events
    CUSTOMS_DECLARATION_SUBMITTED,
    CUSTOMS_DECLARATION_CLEARED,
    CUSTOMS_DECLARATION_REJECTED,
    CUSTOMS_DECLARATION_HELD,
    CUSTOMS_DUTIES_REMINDER,

    // Court events
    COURT_CASE_FILED,
    COURT_VERDICT_ISSUED,
    COURT_FINE_ISSUED,
    FINE_OVERDUE,
    HEARING_REMINDER,
    DOCUMENT_ACCEPTED,
    FINE_PAYMENT_PENDING_VERIFICATION,
    FINE_PAYMENT_CONFIRMED,

    // Pension events
    PENSION_ACCOUNT_OPENED,
    CONTRIBUTION_RECEIVED,
    CONTRIBUTION_DUE_REMINDER,
    PENSION_NOW_ELIGIBLE,
    PENSION_APPROVED,
    PENSION_PAYMENT_SCHEDULED,
    PENSION_ACCOUNT_CLOSED,

    // Authentication events
    OTP_LOGIN,
    NEW_SESSION_DETECTED,
    SESSION_REVOKED_BY_ADMIN,

    // Data requests
    DATA_REQUEST_RECEIVED,
    DATA_REQUEST_APPROVED,
    DATA_REQUEST_REJECTED,
    DATA_REQUEST_PARTIAL,

    // Appointment events
    APPOINTMENT_BOOKED,
    APPOINTMENT_REMINDER,
    APPOINTMENT_CANCELLED_BY_CITIZEN,
    APPOINTMENT_CANCELLED_BY_OFFICE,
    APPOINTMENT_COMPLETED,
    WAITLIST_SLOT_AVAILABLE,
    WAITLIST_EXPIRED,

    // Digital Signature events
    DOCUMENT_SIGNED,
    SIGNATURE_REVOKED,
    SIGNATURE_VERIFIED_BY_THIRD_PARTY,

    // Banking API consent events
    BANKING_CONSENT_REQUESTED,
    BANKING_CONSENT_APPROVED,
    BANKING_CONSENT_REJECTED,
    BANKING_CONSENT_EXPIRED,
    BANKING_DATA_ACCESSED,

    // Analytics / reporting events
    DAILY_REPORT_READY,
    WEEKLY_REPORT_READY,
    REPORT_GENERATED,

    // Document Wallet events
    CERTIFICATE_GENERATED,
    CERTIFICATE_VERIFIED_BY_THIRD_PARTY,

    // Status Tracker events
    TRACKING_STATUS_UPDATED,
    TRACKING_ITEM_COMPLETED,

    // Vehicle registry events
    VEHICLE_REGISTERED,
    VEHICLE_TRANSFER_APPROVED,
    VEHICLE_TRANSFER_REJECTED,
    VEHICLE_INHERITANCE_PENDING,
    INSURANCE_EXPIRING_SOON,
    INSPECTION_DUE_SOON,
    VEHICLE_REPORTED_STOLEN
}
