package com.sanly.bridge.entity;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDateTime;
import java.util.UUID;

/**
 * An anomaly alert generated by the AnomalyDetectionService after a suspicious
 * exchange pattern is detected. Records are immutable once created except for
 * the status/reviewedBy/reviewedAt fields (set when an admin reviews the alert).
 */
@Entity
@Table(name = "anomaly_alerts",
    indexes = {
        @Index(name = "idx_alert_institution", columnList = "institution_code"),
        @Index(name = "idx_alert_status",      columnList = "status"),
        @Index(name = "idx_alert_severity",    columnList = "severity"),
        @Index(name = "idx_alert_type",        columnList = "alert_type"),
        @Index(name = "idx_alert_detected_at", columnList = "detected_at DESC"),
    }
)
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class AnomalyAlert {

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(name = "alert_id", updatable = false, nullable = false)
    private UUID alertId;

    @Column(name = "institution_code", length = 50, nullable = false)
    private String institutionCode;

    @Enumerated(EnumType.STRING)
    @Column(name = "alert_type", length = 50, nullable = false)
    private AnomalyType alertType;

    @Column(name = "description", columnDefinition = "TEXT", nullable = false)
    private String description;

    @Enumerated(EnumType.STRING)
    @Column(name = "severity", length = 20, nullable = false)
    private AlertSeverity severity;

    @Column(name = "national_id_involved", length = 30)
    private String nationalIdInvolved;

    @Column(name = "detected_at", nullable = false)
    private LocalDateTime detectedAt;

    @Enumerated(EnumType.STRING)
    @Column(name = "status", length = 20, nullable = false)
    @Builder.Default
    private AlertStatus status = AlertStatus.OPEN;

    @Column(name = "reviewed_by", length = 200)
    private String reviewedBy;

    @Column(name = "reviewed_at")
    private LocalDateTime reviewedAt;
}
