package com.sanly.documents.entity;

public enum DocumentType {
    BIRTH_CERTIFICATE,
    MARRIAGE_CERTIFICATE,
    DEATH_CERTIFICATE,
    DRIVING_LICENSE,
    NATIONAL_ID,
    DIPLOMA,
    PROPERTY_DEED,
    BUSINESS_REGISTRATION,
    TAX_CLEARANCE,
    CRIMINAL_CLEARANCE,
    MEDICAL_CLEARANCE,
    CUSTOMS_CLEARANCE,
    COURT_ORDER,
    PENSION_CERTIFICATE,
    VEHICLE_REGISTRATION,
    SOCIAL_BENEFIT_LETTER
}
