package com.sanly.documents.entity;

public enum ItemType {
    LICENSE_APPLICATION,
    BUSINESS_REGISTRATION,
    PROPERTY_TRANSFER,
    BENEFIT_CLAIM,
    COURT_CASE,
    CUSTOMS_DECLARATION,
    APPOINTMENT,
    DIPLOMA_APPLICATION,
    PENSION_APPLICATION,
    SIGNATURE_REQUEST,
    DATA_DELETION_REQUEST,
    PRESCRIPTION,
    FINE_PAYMENT,
    VEHICLE_TRANSFER
}
