-- SANLY Bridge — V7: Anomaly detection alerts (Anti-Corruption Feature 2)
-- Stores alerts generated by automated pattern detection on exchange logs.
-- Detects: volume spikes, repeated citizen queries, off-hours sensitive access,
-- unaccompanied ROUTINE_CHECK on sensitive data, bulk scans, and probing.

CREATE TABLE IF NOT EXISTS anomaly_alerts (
    alert_id            UUID            NOT NULL DEFAULT gen_random_uuid(),
    institution_code    VARCHAR(50)     NOT NULL,
    alert_type          VARCHAR(50)     NOT NULL,
    description         TEXT            NOT NULL,
    severity            VARCHAR(20)     NOT NULL
                            CHECK (severity IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),
    national_id_involved VARCHAR(30),
    detected_at         TIMESTAMP       NOT NULL DEFAULT NOW(),
    status              VARCHAR(20)     NOT NULL DEFAULT 'OPEN'
                            CHECK (status IN ('OPEN', 'REVIEWED', 'DISMISSED')),
    reviewed_by         VARCHAR(200),
    reviewed_at         TIMESTAMP,

    CONSTRAINT pk_anomaly_alerts PRIMARY KEY (alert_id)
);

CREATE INDEX IF NOT EXISTS idx_alert_institution ON anomaly_alerts (institution_code);
CREATE INDEX IF NOT EXISTS idx_alert_status      ON anomaly_alerts (status);
CREATE INDEX IF NOT EXISTS idx_alert_severity    ON anomaly_alerts (severity);
CREATE INDEX IF NOT EXISTS idx_alert_type        ON anomaly_alerts (alert_type);
CREATE INDEX IF NOT EXISTS idx_alert_detected_at ON anomaly_alerts (detected_at DESC);
